name: Destroy - Infra (Dia 1 + Dia 2)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Digite "destroy" para confirmar a destruicao dos recursos'
        required: true
      target:
        description: 'Escopo do destroy: all (tudo) ou aci-only (so a webapp)'
        required: true
        default: 'aci-only'
        type: choice
        options:
          - all
          - aci-only

env:
  TF_VAR_mysql_admin_password: ${{ secrets.MYSQL_ADMIN_PASSWORD }}

jobs:
  terraform-destroy:
    if: github.event.inputs.confirm == 'destroy'
    runs-on: ubuntu-latest
    environment: producao-destroy
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: terraform init

      - name: Destroy apenas o ACI
        if: github.event.inputs.target == 'aci-only'
        run: terraform destroy -auto-approve -target=azurerm_container_group.webapp

      - name: Destroy de toda a infraestrutura
        if: github.event.inputs.target == 'all'
        run: terraform destroy -auto-approve
